version: "3.3"
services:
  nginx:
    image: tutum/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./docker/conf/vhost.conf:/etc/nginx/sites-available/default
      - ./docker/conf/vhost.conf:/etc/nginx/sites-enabled/default
      - ./:/var/www/my-blog

  php-fpm:
    build:
      context: .
      dockerfile: /docker/Fpm.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/my-blog
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - /var/www/my-blog:/var/www/my-blog
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=my_blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions